backend:
  name: webriq-api #netlify-api
  repo: webriq/webriqpage-flymycommunity-landing1 # Updated repo details ### Original: owner/repo
  branch: master

production:
  backend:
    name: webriq-api
    repo: webriq/webriqpage-flymycommunity-landing1 # Updated repo details ### Original: owner/repo # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

responsive_images: true

collections: # A list of collections the CMS should be able to edit
  - name: "sitedata"
    label: "Site Information"
    create: false
    files:
      - name: "sitedata"
        label: "Site Information"
        file: "data/site.json"
        description: "edit site setting"
        fields:
          - label: "Site Information"
            name: "sitedata"
            widget: "list"
            fields:
              - {label: "Website Title", name: "sitename", widget: "string"}
              - {label: "Website Meta Description", name: "metadesc", widget: "string"}
              - {label: "Website Meta Keywords", name: "metakeyword", widget: "string"}
              - {label: "Website Author", name: "metauthor", widget: "string"}
              - {label: "Website Logo", name: "logo", widget: "image", media_folder: "assets/img", dom_data: [{ target: ".logo img", attr: "src"}]}


          - label: "Content Information"
            name: "content"
            widget: "list"
            fields:
              - {label: "Your Email", name: "email", widget: "string", dom_data: [{ target: ".col.mail a", attr: "mailto" }, { target: ".col.mail a", attr: "text" }]}
              - {label: "Your Contact Phone Number", name: "linkcont", widget: "string", dom_data: [{target: ".phone", attr: "href"}, {target: ".phone b", attr: "text"}]}
              - {label: "Video ID", "name": "videoid", widget: "string", dom_data: [{ target: ".col.btnplay a", attr: "href", value_pattern: "//vimeo.com/{0}" }, { target: "#main-slider .video-foreground iframe", attr: "src", value_pattern: "https://player.vimeo.com/video/{0}?background=1" },{"attr":"data-izimodal-iframeurl","target":".modais", "value_pattern":"//vimeo.com/{0}"}]}
              - {label: "Video Subheading", name: "slidertext1", widget: "string", dom_data: [{ target: ".video-subheading", attr: "text"}] }
              - {label: "Video Heading", name: "slidertext2", widget: "string", dom_data: [{ target: ".video-heading", attr: "text"}]}

          - label: "About Information"
            name: "about"
            widget: "list"
            fields:
              - {label: "Video Title", name: "abouttext1", placeholder_text: "Edit video title", default_text: "Crystal Park - FMC ", widget: "string", dom_data: [{ target: ".video-title", attr: "text"}]}
              - {label: "Video Description", name: "abouttext2", placeholder_text: "Edit video description", default_text: "Crystal Park is a private gated mountain community within the Pikes Peak region. Located above Colorado Springs and adjacent to Manitou Springs.....", widget: "string", dom_data: [{ target: ".video-description", attr: "text"}]}
  - name: "biography"
    label: "Agent Biography"
    create: false
    files:
      - name: "biography"
        label: "Agent Biography"
        file: "data/site.json"
        description: "edit agent biography"
        fields:
          - label: "Agent Biography"
            name: "biography"
            widget: "list"
            fields:
              - {label: "Id", name: "num", widget: "number"}
              - {label: "Profile Image", name: "image", widget: "image", media_folder: "assets/img"}
              - {label: "Agent Name", name: "fullname", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Specialties", name: "specialties", widget: "string"}
              - {label: "License", name: "license", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Phone Number", name: "phonenumber", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Website", name: "website", widget: "string"}
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
              - {label: "Pinterest", name: "pinterest", widget: "string"}
              - {label: "Twitter", name: "twitter", widget: "string"}
              - {label: "Linkedin", name: "linkedin", widget: "string"}
              - {label: "Shortdesc", name: "shortdesc", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}

              
